FROM dunglas/frankenphp:php8.3

WORKDIR /app

COPY . /app

RUN docker-php-ext-install pdo_mysql

ENV SERVER_NAME=:8000

EXPOSE 8000

CMD ["frankenphp", "php-server", "--listen", ":8000", "--root", "/app/public"]